import Track from '#models/track'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Track.createMany([
      {
        name: 'Nogaro',
        slug: 'nogaro',
        countryId: 1,
        city: 'Nogaro',
        adress: "Av. de l'Autodrome, 32110 Nogaro, France",
        length: 3636,
        turn: '14 (5 à gauche et 9 à droite)',
        bestLapTime: '1.20.160',
        bestLapTimePilote: 'Alessandro Zanardi',
        width: 9.5,
        maxDb: 102,
        infos: '6600 m2 de bâtiments couverts',
      },
      {
        name: 'Pau Arnos',
        slug: 'pau-arnos',
        countryId: 1,
        city: 'Arnos',
        adress: 'Circuit Arnos, Petrou, 64370 Arnos, France',
        length: 3030,
        turn: '12 (7 à droite et 5 à gauche)',
        bestLapTime: '1.10.870',
        bestLapTimePilote: 'Giedo Van der Garde',
        width: '9 a 12',
        maxDb: 102,
        infos:
          '1 tracé principal de 3 030 mètres (5 tracés dérivés de 3 030 mètres & 600 mètres), circuit de karting',
      },
      {
        name: 'Navarra',
        slug: 'navarra',
        countryId: 2,
        city: 'Los Arcos',
        adress: 'Calle Malvasia 5, 31210 Los Arcos Spain',
        turn: '15 (7 à droite et 5 à gauche)',
        length: 3933,
        bestLapTime: '1.38.417',
        bestLapTimePilote: 'Cauvin Dominique',
        width: '9 a 12',
        maxDb: 102,
        infos: 'Restaurant sur place, circuit de karting',
      },
      {
        name: 'Motorland Aràgon',
        slug: 'motorland-aragon',
        countryId: 2,
        city: 'Alcañiz',
        adress: 'Crta, A-2404, km 1, 44600 Alcaniz Spain',
        turn: '17 (7 à droite et 10 à gauche)',
        length: 5078,
        bestLapTime: '1.38.976',
        bestLapTimePilote: 'Raffaele Marciello',
        width: 15,
        maxDb: 102,
        infos: 'Restaurant sur place, circuit de karting',
      },
      {
        name: 'Alcarras',
        slug: 'alcarras',
        countryId: 2,
        city: 'Alcarras',
        adress: 'km, Av. de Valmanya, 13, 25180 Alcarràs, Lleida, Spain',
        turn: '14 (10 à gauche, 4 à droite)',
        length: 3743,
        width: '14 a 15',
        maxDb: 102,
        infos: 'Circuit de karting (1km17, 13 virages 8 à gauche, 5 à droite)',
      },
      {
        name: 'Jerez',
        slug: 'jerez',
        countryId: 2,
        city: 'Jerez',
        adress:
          'Carretera de Arcos-Jerez de la Frontera, Km 10, 11405 Jerez de la Frontera, Cádiz, Espagne',
        turn: '13 (5 à gauche, 8 à droite)',
        length: 4428,
        bestLapTime: '1.15.650',
        bestLapTimePilote: 'Michael Schumacher',
        width: '14 a 15',
      },
      {
        name: 'Calafat',
        slug: 'calafat',
        countryId: 2,
        city: 'Calafat',
        adress: 'Urb. Calafat, Circuit, 43860 Calafat, Tarragona, Espagne',
        turn: '19',
        length: 3250,
        width: '14 a 15',
      },
      {
        name: 'Dijon',
        slug: 'dijon',
      },
      {
        name: 'Misano',
        slug: 'misano',
        countryId: 3,
        city: 'Misano',
        adress: '',
        turn: '16 (6 à gauche, 10 à droite)',
        length: 4230,
        width: 12,
      },
      {
        name: 'Autodromo Internazionale del Mugello',
        slug: 'autodromo-internazionale-del-mugello',
        countryId: 3,
        city: 'Mugello',
        adress: '',
        turn: '15 (6 à gauche, 9 à droite)',
        length: 5250,
        width: 14,
      },
      {
        name: ' Magny Cours',
        slug: 'magny-cours',
      },
      {
        name: 'Ales',
        slug: 'ales',
      },
      {
        name: 'Lusail International Circuit',
        slug: 'lusail-international-circuit',
        countryId: 11,
        city: '',
        adress: '',
        turn: '16 (6 à gauche, 10 à droite)',
        length: 5380,
        width: 12,
      },
      {
        name: 'Portimão - Autódromo Internacional do Algarve',
        slug: 'portimao-autodromo-internacional-do-algarve',
        countryId: 5,
        city: '',
        adress: '',
        turn: '15 (6 à gauche, 9 à droite)',
        length: 4590,
        width: 18,
      },
      {
        name: 'Circuit Of The Americas',
        slug: 'circuit-of-the-americas',
        countryId: 12,
        city: '',
        adress: '',
        turn: '20 (11 à gauche, 9 à droite)',
        length: 5510,
        width: 15,
      },
      {
        name: 'Circuito de Jerez - Ángel Nieto',
        slug: 'circuito-de-jerez-angel-nieto',
        countryId: 2,
        city: 'Jerez',
        adress: '',
        turn: '13 (5 à gauche, 8 à droite)',
        length: 4620,
        width: 11,
      },
      {
        name: 'Le Mans',
        slug: 'le-mans',
        countryId: 1,
        city: 'Le Mans',
        adress: '',
        turn: '14 (5 à gauche, 9 à droite)',
        length: 4190,
        width: 13,
      },
      {
        name: 'Circuit de Barcelona-Catalunya',
        slug: 'circuit-de-barcelona-catalunya',
        countryId: 2,
        city: 'Barcelona',
        adress: '',
        turn: '14 (6 à gauche, 8 à droite)',
        length: 4660,
        width: 12,
      },
      {
        name: 'TT Circuit Assen',
        slug: 'tt-circuit-assen',
        countryId: 9,
        city: 'Assen',
        adress: '',
        turn: '18 (6 à gauche, 12 à droite)',
        length: 4542,
        width: 14,
      },
      {
        name: 'Sachsenring',
        slug: 'sachsenring',
        countryId: 18,
        city: 'Hohenstein-Ernstthal',
        adress: '',
        turn: '13 (10 à gauche, 3 à droite)',
        length: 3671,
        width: 12,
      },
      {
        name: 'Silverstone Circuit',
        slug: 'silverstone-circuit',
        countryId: 10,
        city: 'Silverstone',
        adress: '',
        turn: '18 (8 à gauche, 10 à droite)',
        length: 5891,
        width: 15,
      },
      {
        name: 'Red Bull Ring',
        slug: 'red-bull-ring',
        countryId: 11,
        city: 'Spielberg',
        adress: '',
        turn: '11 (3 à gauche, 8 à droite)',
        length: 4350,
        width: 12,
      },
      {
        name: 'Mandalika International Street Circuit',
        slug: 'mandalika-international-street-circuit',
        countryId: 19,
        city: 'Kuta Mandalika',
        adress: '',
        turn: '17 (6 à gauche, 11 à droite)',
        length: 4300,
        width: 15,
      },
      {
        name: 'Motegi Twin Ring',
        slug: 'motegi-twin-ring',
        countryId: 11,
        city: 'Motegi',
        adress: '',
        turn: '14 (6 à gauche, 8 à droite)',
        length: 4801,
        width: 15,
      },
      {
        name: 'Phillip Island',
        slug: 'phillip-island',
        countryId: 5,
        city: 'Phillip Island',
        adress: '',
        turn: '12 (5 à gauche, 7 à droite)',
        length: 4445,
        width: 13,
      },
      {
        name: 'Chang International Circuit',
        slug: 'chang-international-circuit',
        countryId: 20,
        city: 'Buriram',
        adress: '',
        turn: '12 (5 à gauche, 7 à droite)',
        length: 4554,
        width: 12,
      },
      {
        name: 'Petronas Sepang International Circuit',
        slug: 'petronas-sepang-international-circuit',
        countryId: 7,
        city: 'Sepang',
        adress: '',
        turn: '15 (5 à gauche, 10 à droite)',
        length: 5543,
        width: 16,
      },
      {
        name: 'Circuit Ricardo Tormo',
        slug: 'circuit-ricardo-tormo',
        countryId: 2,
        city: 'Valencia',
        adress: 'Salida, Autovía del Este, 334, 46380 Cheste, Valencia, Espagne',
        turn: '14 (9 à gauche, 5 à droite)',
        length: 4005,
        width: 12,
        maxDb: 118,
        bestLapTime: '1:29.401',
      },
    ])
  }
}
